# fly.toml file generated for cypher-elections

app = "cypher-elections"
primary_region = "iad"

[build]
  builder = "heroku"
  buildpacks = ["buildpacks/nodejs", "buildpacks/npm"]

[env]
  LOG_LEVEL = "info"
  NODE_ENV = "production"

[deploy]
  release_command = "npm run build"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 9090
